---
- name: Configure and install Nginx
  hosts: nginx_servers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx service is running and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes