AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  QuickDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: env0-sam-to-cfn-testing-table
      Tags:
        Department: Engineering
        AppType: Serverless
