AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  QuickDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub "env0-sam-demo-${AWS::StackName}"
      Tags:
        Department: Engineering
        AppType: Serverless
